### ISSUE TITLE
this.app.loginRedirect not working properly

### ISSUE THREAD

**Issue by uma075** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#10]
I need page instead of pop up so I converted loginPopup to loginRedirect but it is not working. 
Actually I think, on redirect it is loosing its state and redirecting to the page as a new instance.
can you please provide some example for loginRedirect?

**Comment by jmprieur** [comment]
I suggest you have a look at https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html to understand how to use loginRedirect.

**Comment by imchaitanya9** [comment]
I tried it. and I am using B2C instead of Graph, but not able to generate access Token.

**Comment by parakhj** [comment]
Check out [this article](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens) if you're having difficulties obtaining an access token

**Comment by bahram-zarrin** [comment]
Hi, do you have any example how I can login with B2C within a Vue.js app?

**Comment by pvrao80** [comment]
I tried to use this code, it worked well on the local host. But when i moved the app and web API to azurewebsites.net, the login button opens another similar HTML popup window page, when the login button in the second window is clicked, the Azure AD B2C authentication opens - on providing the right password, it returns the last picture below.

Home page opens this page --> Correct behaviour
![image](https://user-images.githubusercontent.com/27910205/33223333-6b1bed18-d12c-11e7-918b-83a6159c310f.png)


Once i click on Login button, it pops another HTML Window with same contents & Login button with the following in address bar
https://pvr3.azurewebsites.net/#error=redirect_uri_mismatch&error_description=AADB2C90006%3a+The+redirect+URI+%27http%3a%2f%2fpvr3.azurewebsites.net%2f%27+provided+in+the+request+is+not+registered+for+the+client+id+%279cc6c52c-a705-4539-aeb2-d662c860c1c5%27.%0d%0aCorrelation+ID%3a+528008e9-3137-45a3-b720-ab56d7f2cc74%0d%0aTimestamp%3a+2017-11-24+20%3a00%3a22Z%0d%0a&state=d14a150d-c7b3-4072-a74d-225663d998d3

Login from this page works perfectly and i get the following page
![image](https://user-images.githubusercontent.com/27910205/33223341-7ae536a0-d12c-11e7-85ec-0fa66fcae9c6.png)

***********
Update - when used the link https://pvr3.azurewebsites.net, the functionality works perfectly. How can i redirect pvr.azurewebsites.net to Https://pvr3.azurewebsites.net ??

Can you please help me debug this issue ??

**Comment by pvrao80** [comment]
Update - I could force redirect http to https by adding a Web.config file in the root using Kudu, refer following link. Could you add to the web.config to Github files ?
https://www.ssl2buy.com/wiki/http-to-https-redirect-using-htaccess-or-web-config

**Comment by tompi** [comment]
Also struggling with redirectLogin, it works ALMOST all of the time :( 

The link from @jmprieur seemed very promising, but alas, it is removed. Cant find ANY documentation on how to use redirectLogin(I can not really understand that anybody would use a popup for login on an actual production site...)

**Comment by jmprieur** [comment]
@tompi : I believe the new link is https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/samples/VanillaJSTestApp/index_LoginPopup.html

adding @navyasric to confirm and share links on documentation on how to use the LoginPopup

**Comment by navyasric** [comment]
@tompi If you are looking for the redirect login method you can find it here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/samples/VanillaJSTestApp/index_LoginRedirect.html

The login with popup sample is here as pointed out above: 
 https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/samples/VanillaJSTestApp/index_LoginPopup.html

You can read further about using the Login APIs in MSAL.js wiki: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Public-APIs#login-apis

**Comment by sameerag** [comment]
**Updating sample links for redirect:**

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/VanillaJSTestApp/index_redirect.html

In general msal usage samples now moved to: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples

Please open a new issue if this is still a concern.

Also tagging with #48 so we ensure covering this use case when the samples are updated.
