### ISSUE TITLE
HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by HoussemDellai** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#12]
When I click the login button: I get : HTTP Error 400. The size of the request headers is too long.
Here's the url:
https://login.microsoftonline.com/te/fabrikamb2c.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Ffabrikamb2c.onmicrosoft.com%2Fdemoapi%2Fdemo.read%20openid%20profile&client_id=e760cab2-b9a1-4c0d-86fb-ff7084abd902&redirect_uri=http%3A%2F%2Flocalhost%3A6420%2F&state=dba15c86-8a33-46c6-8f7e-023201425485&nonce=b8d49401-0ecb-4570-bc4c-f3a054c8b025&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.1.1&client-request-id=ea827f7f-fffc-44f5-8652-e030c699c924&prompt=select_account&response_mode=fragment

**Comment by gavinbarron** [comment]
I guess this is happening in Chrome?
I get this all the time with the AAD login sites and not just the MSAL library. The 'fix' is to delete all the cookies for login.microsoftonline.com based on my experience.

**Comment by spottedmahn** [comment]
Agreed @gavinbarron, [more details here](https://stackoverflow.com/a/46250877/185123).

**Comment by jennyf19** [comment]
@HoussemDellai @gavinbarron @spottedmahn 
The fix for this is using b2clogin.com, and not login.microsoftonline.com. With login.microsoftonline.com, the cookies would accumulate, but w/b2clogin.com B2C condenses the cookies. If you want more info on this, lmk. Thanks.

closing.
