### ISSUE TITLE
Eliminate Popup

### ISSUE THREAD

**Issue by pvrao80** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#13]
On click of login, this code opens the AD B2C authentication as a pop up. Could you guide me to change this within the same window rather than a popup ?

**Comment by gavinbarron** [comment]
Try the loginRedirect insteam of the loginPopup method (line 53 of index.html)

**Comment by kwaazaar** [comment]
Why is a popup even attempted? All/most browsers don't allow it.

Also I cannot get the loginRedirect to work: it logs on, but when being posted back to my app, the id_token, which is passed on the URL, is not used. I also cannot find any other samples that actually work out of the box. Is there any decent documentation anywhere?
