### ISSUE TITLE
Issues with MSAL.js using IE11 in corporate environments (Enable Protected Mode)

### ISSUE THREAD

**Issue by chesterhartin** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#14]
Hello! I am having an issue with the sample (as is) in a corporate environment and can be simulated at home via checking the Enable Protected mode box (which I am unable to do at work due to domain policies (currently showing home setup)

![1](https://user-images.githubusercontent.com/1890420/35185707-234d238e-fdce-11e7-8026-3317939a6b60.PNG)

Running the bat file works great, I'm able to see the page:

![2](https://user-images.githubusercontent.com/1890420/35185708-23682e18-fdce-11e7-8dfe-adb1e0c8f1f2.PNG)

I get a nice friendly popup. I signup or login as normal:

![3](https://user-images.githubusercontent.com/1890420/35185709-2385029a-fdce-11e7-81fa-e993371c1bb0.PNG)

And then I get the parent form, now shown in the popup. 

![4](https://user-images.githubusercontent.com/1890420/35185710-23a33396-fdce-11e7-8a92-94374d373605.PNG)

Watching my console, it appears that things went well until it hit: 

GET / 304 1.550 ms - -
GET /null 200 2.382 ms - 4724

![5](https://user-images.githubusercontent.com/1890420/35185711-23be5da6-fdce-11e7-9476-1c5591427db7.PNG)

Further digging I came across this, which mentions that if you turn off this setting - voila, it works:

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/16

Which is all well and good if you are allowed to, but alas -- corporate policies. But as stated above, that only works if you have the ability to do so. 

I tried this as a redirect as well and updating to the latest msl.js version, but no luck.

The only "hack" I could find was to run IE 11 as administrator (if you have the permission). Any suggestions?

**Comment by anirudhholla** [comment]
Even I am facing the same issue on IE11, any suggestions ?

**Comment by edmondchingicg** [comment]
Is there any update on this issue?

**Comment by pkanher617** [comment]
@chesterhartin @anirudhholla @edmondchingicg Sorry for the delay in response. We will take a look at this issue and get back as soon as we can.

**Comment by derisen** [comment]
This issue has been stale for some time, while MSAL.js has been updated heavily since. Closing this, but let us know if the issue still persists @chesterhartin @anirudhholla @edmondchingicg

**Comment by PvanHengel** [comment]
Hi we are seeing this issue, anyone have an update need help ASAP!
