### ISSUE TITLE
Authority string is being incorrectly appended to

### ISSUE THREAD

**Issue by pconnell99** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#15]
When I am trying to set an authority string the call to the server is corrupted.

Example:-
```
this.applicationConfig = {
      clientID: '<clientid>',
      authority:'https://login.microsoftonline.com/<mytenant>.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_GPlus',
      graphScopes: ['user.read']
    };
```
The authority is readable in a browser and returns a policy.  However, when I run the application so:-

```
this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      this.applicationConfig.authority,
      () => {
        // callback for login redirect
      },
      {
        redirectUri
      }
    );
```
The popup closes and the browser reports a 400 (Bad Request) for the URL `https://login.microsoftonline.com/<mytenant>.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=b2c_1_gplus/v2.0/.well-known/openid-configuration`

Am I setting the authority incorrectly or is the library appending the string?

**Comment by josmithua** [comment]
It's 8 months later, but for anyone else looking at this in Nov 2018, the authority should be in the form:
`https://login.microsoftonline.com/tfp/<tenant-name>.onmicrosoft.com/<policy-name/v2.0/.well-known/openid-configuration>`

or

`https://<tenant-name>.b2clogin.com/tfp/<tenant-name>.onmicrosoft.com/<policy-name>/v2.0/.well-known/openid-configuration` (this is the preferred form going forward, see [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin))

It appears as though if you do not have the `/v2.0/.well-known/openid-configuration` part at the end it will append it on for you, hence why the OP was getting his error (not to mention the URL was wrong)
