### ISSUE TITLE
Token Expiry and Renewal

### ISSUE THREAD

**Issue by ganeshthiagarajan** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#19]
Do we have any sample codes that indicate how to check if the token has expired and also how to renew the token when it is expired using MSAL for SPA?

**Comment by spottedmahn** [comment]
The MSAL.js library handles that for you 😊

See [`getCachedToken()`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/89307c1cb9f075f24a48aed77d9502824a9c346b/lib/msal-core/src/UserAgentApplication.ts#L1703):

```typescript
const expired = Number(accessTokenCacheItem.value.expiresIn);
// If expiration is within offset, it will force renew
const offset = this._clockSkew || 300;
if (expired && (expired > Utils.now() + offset)) {
	return {
	  errorDesc: null,
	  token: accessTokenCacheItem.value.accessToken,
	  error: null
	};
} else {
	this._cacheStorage.removeItem(JSON.stringify(filteredItems[0].key));
	return null;
}
```
---
I don't see it documented in the [wiki though](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki).  Perhaps an issue should be opened to address this 🤔?

**Comment by jennyf19** [comment]
@spottedmahn do you know if this information was included in the wiki? thanks.

**Comment by spottedmahn** [comment]
looks like it 😀: [Q3. How to renew tokens with MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q3-how-to-renew-tokens-with-msaljs)

**Comment by jennyf19** [comment]
Awesome! Thanks for the quick response @spottedmahn will close.
