### ISSUE TITLE
Azure AD B2C Msal.js acquireTokenSilent Performance issue

### ISSUE THREAD

**Issue by srivathsanvlb** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#20]
Hi Azure team,

I am facing performance issues while using msal.js. I have all the details over here

https://social.msdn.microsoft.com/Forums/en-US/22a53bc6-cd7d-4226-ba61-3ba84368dd8b/azure-ad-b2c-msaljs-acquiretokensilent-performance-issue?forum=WindowsAzureAD

Appreciate a quick turn around. Thanks in advance.

**Comment by nehaagrawal** [comment]
@srivathsanvlb Can you please mention what version of library you are using? 
Also could you please directly open an issue on MSAL's github page directly in future. We are more active there. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues

**Comment by srivathsanvlb** [comment]
Hi @nehaagrawal 

First of all, thanks for the quick reply.

I am using https://secure.aadcdn.microsoftonline-p.com/lib/0.1.3/js/msal.min.js

I can open this in the above said thread
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues

Let me know if I have to close this and open there now.

**Comment by srivathsanvlb** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/393

**Comment by jennyf19** [comment]
looks like this was addressed. closing
