### ISSUE TITLE
CORS Error 

### ISSUE THREAD

**Issue by arahate** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#22]
Getting CORS Error, How to fix CORS set Azure B2C directory?

![capturecors](https://user-images.githubusercontent.com/10863978/50009023-d8802e80-ffdb-11e8-9fbb-3e2d56bee1ec.PNG)

**Comment by pascalgn** [comment]
I think the issue is the 404: Maybe tenant ID or signup policy name "b2c_1_siupin" are wrong. In that case Azure returns a 404 and apparently also does not send any CORS headers

**Comment by AnnaShk** [comment]
Hi @arahate,

Did you find the solution for your issue? I'm having the same but in password reset scenario. 

Thank you

**Comment by jennyf19** [comment]
@arahate did you get this figured out?

**Comment by leonbrag** [comment]
I have the same issue, when setting up locally. I can login, but cannot invoke API:
![image](https://user-images.githubusercontent.com/5290089/65063938-255eb000-d934-11e9-94b7-719b423181b2.png)

**Comment by jennyf19** [comment]
@jmprieur thoughts on this?

**Comment by jmprieur** [comment]
@leonbrag : is there anywhere in your code where http://localhost:3000 is mentioned? it's nowhere in the sample, and I'm wondering where this is coming from:
cc: @jennyf19

**Comment by leonbrag** [comment]
In my case SPA was on Web API were on listening on the different port. So error was expected. Error was fixed by allowing cross domain on Web API:
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "*");

**Comment by jmprieur** [comment]
Closing the issue as there is an answer.

**Comment by jennyf19** [comment]
thanks for the update @leonbrag
