### ISSUE TITLE
Authority uri with b2clogin.com can not work with msal.js v0.2.4

### ISSUE THREAD

**Issue by Iamnvincible** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#23]
I used `npm install msal` and the latest version of msal.js is 0.2.4 rather than 0.1.1
https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/7b68322a9a020cf23197534e677537a7915c7143/index.html#L24

In the applicationConfig fields, `authority` field can not accept `https://{tenant}.b2clogin.com/tfp/{tenant}.onmicrosoft.com/B2C_1_SiUpIn` , and it will print an error:
```
Error during login:
endpoints_resolution_error:Endpoints cannot be resolved
```
If I change the authority field to `"https://login.microsoftonline.com/tfp/{tenant}.onmicrosoft.com/B2C_1_SiupIn",` social account provider's (like Google, GitHub, Microsoft) redirect uri are not correct with my former settings (all the redirect uris are filled with b2c pattern) which will leads to sign in error.

Is there any sample with the msal.js v0.2.4? Thanks.

**Comment by pascalgn** [comment]
Did you use the string `https://{tenant}.b2clogin.com/tfp/{tenant}.onmicrosoft.com/B2C_1_SiUpIn` literally? You should replace `{tenant}` with your tenant name, so it should look like `https://yourb2ctenantname.b2clogin.com/tfp/yourb2ctenantname.onmicrosoft.com/B2C_1_SiUpIn`

**Comment by Iamnvincible** [comment]
finally, I solved this problem by adding a attribute `validateAuthority: false`. 
Thanks.
```
var clientApplication = new Msal.UserAgentApplication(
  applicationConfig.clientID,
  applicationConfig.authority,
  function(errorDesc, token, error, tokenType) {
    // Called after loginRedirect or acquireTokenPopup
  },
{
    validateAuthority: false
  }
);
```
