### ISSUE TITLE
User 'undefined' logged-in

### ISSUE THREAD

**Issue by smoms** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#24]
Hi,
i've followed the tutorial and with my WebAPi i get "User 'undefined' logged-in" after the login. Why user is undefined?

**Comment by aszalacinski** [comment]
I see that none of the specified claims coming back. All are undefined. I wanted to get back Given Name, Sur Name, Email address and username; all undefined.

**Comment by aszalacinski** [comment]
Nevermind... its in the IdToken returned from the endpoint. @smoms look inside the idToken on the response.

**Comment by jennyf19** [comment]
@smoms are you still having an issue w/this?

**Comment by smoms** [comment]
too long ago. I do not remember anymore.

**Comment by jennyf19** [comment]
@smoms sorry it took us so long to engage with you. will do better moving forward.
if you continue to have issues, please reopen or create a new issue. thanks!

**Comment by idegollado** [comment]
I have this problem too.
![image](https://user-images.githubusercontent.com/25804691/65465525-27d47480-de22-11e9-825b-48c64620efe1.png)

**Comment by jennyf19** [comment]
@SeniorID Are you running the sample as-is? which idp are you signing in with?
