### ISSUE TITLE
Update MSAL to latest version

### ISSUE THREAD

**Issue by aszalacinski** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#25]
The MSAL being used on this example if from 2017... version 0.1.1... a lot appears to have changed since then...

**Comment by navyasric** [comment]
The sample has been updated to use MSAL.js 1.0.0. Please try it out. Thanks.

**Comment by mmacy** [comment]
For reference, the PR with the msal.js 1.0.0 was #26
