### ISSUE TITLE
ASP.Net Core WebApi Sample

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#3]
I see there is a sample for [Node.js](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi).  Is there one for ASP.Net Core?

**Comment by parakhj** [comment]
For the server side? Does this help - https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi?
