### ISSUE TITLE
Call Web API always fails with 401

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#33]
![image](https://user-images.githubusercontent.com/12273384/61186659-c6449c80-a65f-11e9-9fc5-15e6f3765b16.png)

I get this with pretty much any identity provider. I suspect this is because the web api has not been updated to work with b2clogin.com, even though there is a PR for this (open since Jan)

**Comment by jennyf19** [comment]
[have identified the issue, will be fixed this week](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/36)

**Comment by bgavrilMS** [comment]
Very cool, lots of happy customers!
