### ISSUE TITLE
Instructions for using own tenant are not up to date 

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#34]
Step 5, substep 3 shows login.microsoftonline.com instead of b2clogin
The little code snipped on step5 shows a single config object, but the code has 2 config objects: 

```js

```
![image](https://user-images.githubusercontent.com/12273384/61315417-9da2db00-a7f6-11e9-8c15-004429371261.png)

**Comment by jmprieur** [comment]
do you want to propose a quick PR, @bgavrilMS ?

**Comment by jennyf19** [comment]
I merged your PR which I think addressed this @bgavrilMS
