### ISSUE TITLE
Feature request: Catching errors returned by B2C. 

### ISSUE THREAD

**Issue by agrabhi** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#38]
The sample should also tell how the errors returned from B2C can be caught and acted upon. 

For example see below question 
https://stackoverflow.com/questions/57670399/azure-active-directory-b2c-catching-error-from-invitation-page

**Comment by sameerag** [comment]
@agrabhi As discussed, this may need to take some dependency on the B2C dev team, FYI @ktsakas and me are working on improving the sample with more complex use-cases and track this as a part of the effort.

**Comment by sameerag** [comment]
tagging this with #48
