### ISSUE TITLE
Sample not working when using ADFS as the ADB2C identity provider

### ISSUE THREAD

**Issue by jmereaux** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#40]
Hi,

We have an Azure ADB2C instance which is configured with an ADFS as the backend IdP.

When using this sample, clicking on the login button launches a popup displaying our custom login form. On this form we can click on a `Login with ADFS` button, which redirects to the ADFS login page.

When logging into the ADFS, the browser gets redirected to the SPA, but we are not logged in. 
We can see the following error in the browser console:

```
Refused to display 'https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/b2c_1a_emlyon_default_signuporsignin/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2F<tenant>.onmicrosoft.com%2Ftest-api%2Fuser_impersonation%20openid%20profile&client_id=3d98c45a-eb05-4415-a5b9-4e94f56f3e7a&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=7b45ee7b-79f2-414f-a512-57c3e2d47dfb&nonce=a1b08caf-07fa-47b6-a00e-05fcab0626b7&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.1.2&login_req=392f09e8-b0c2-4227-8553-c338827f30e6-b2c_1a_default_signuporsignin&domain_req=bffecd0e-2a18-4e8a-8549-e781affd40cb&domain_hint=organizations&client-request-id=da6f2fa0-5c20-4ed9-bb79-9acba933bc43&prompt=none' in a frame because it set 'X-Frame-Options' to 'deny'.
```

Any idea on what could be wrong here?
Thanks

**Comment by jennyf19** [comment]
@sameerag @DarylThayil thoughts on this?

@jmereaux do you have a repro you can share?

**Comment by sameerag** [comment]
Well this could be an additional complication with the B2C policies and silent calls (which happen in an iframe); cc @ktsakas, I will investigate further and update.

**Comment by sameerag** [comment]
@jmereaux Can you please share the steps to repro and sample code of your token requests?

**Comment by CodyMorris** [comment]
I'm having the same experience trying to use `acquireTokenSilent` , with a SAML IDP configured in AzureB2C.

If I use `acquireTokenPopup` I do not get this xframe error.

Because you are using ADFS I assume it is also configured using SAML and the guide here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-adfs2016-custom?tabs=applications .   I think I'm in the same boat here.

**Comment by derisen** [comment]
Closing this as this sample is being archived. Please see the [new sample](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa) and/or raise any issues you have at [MSAL.js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues).
