### ISSUE TITLE
Readme needs update

### ISSUE THREAD

**Issue by adebruyne** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#41]
I was following the Readme step by step, but there seems to be some errors in the directions that don't reflect the code. 

Under the **Using your own Azure AD B2C Tenant**, step 3, there is an indication to "update the following variables" including tenantID, clientID and policyName in the index.html of the Node.js Web API sample. 

But in this directory, there is not index.html. There is an index.js, but the variable names don't all match. So, I'm having a little trouble getting the sample up and would love some clarification. Thanks!

**Comment by sameerag** [comment]
@adebruyne Thanks for the feedback. This should be "node server.js" I believe. I will follow up with the team and have this updated asap.

**Comment by sameerag** [comment]
Please expect this to be closed by early next week

**Comment by benheymink** [comment]
Just hit this as well, bit confusing. Are you happy for others to submit a PR to fix the docs?
