### ISSUE TITLE
decouple auth flow from API access

### ISSUE THREAD

**Issue by mmacy** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#42]
In the article [Tutorial: Enable authentication in a single-page application using Azure AD B2C](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-tutorials-spa#error-insufficient-permissions), readers are instructed to modify the sample such that it works with their own B2C tenant. In [part two of the series](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-tutorials-spa-webapi), they're then instructed to register an API application and configure the sample to work with their tenant.

However, at the end of tutorial 1, because they've not yet configured the API portion of the sample, the application displays a permissions error even though they successfully authenticate, and have _not_ selected the **Call Web API** button. This leads to frustration as evidenced by this issue in the azure-docs repo:

https://github.com/MicrosoftDocs/azure-docs/issues/41456 

Requesting here that API access is decoupled from the auth flow, and that a friendly error message is displayed if the **Call Web API** button is selected prior to the customer configuring the API portion.

Cc: @jennyf19

**Comment by jennyf19** [comment]
@sameerag @DarylThayil @pkanher617

**Comment by sameerag** [comment]
Thanks @mmacy  and @jennyf19. The initial sample was worked of the prior model B2C dev team and the `msal js` quickstart provided and we focused on making it functional with the new API of `msal js`. 

I agree with the comments, will be able to work on this soon.

**Comment by jennyf19** [comment]
Thanks @sameerag !

**Comment by DarylThayil** [comment]
@sameerag should we create an issue in our github linked to this so we don't lose it?

**Comment by sameerag** [comment]
Yes @DarylThayil. I plan to address this as a part of our sample/integration test work, I am creating work items in `msal js` github later today. Will link the issue # here once I have it.

**Comment by mmacy** [comment]
Hi @sameerag & @DarylThayil, has the `msal.js` work item been created for this, by chance? We're currently providing a quite sub-optimal experience in the tutorials due to the API access attempt at sign-in, so wondering if we can get this on the TODO list.

Here's the warning message I've added to our tutorial:

![image](https://user-images.githubusercontent.com/13394541/68501349-c66e3680-0212-11ea-9fa8-49bff42424cd.png)

**Comment by sameerag** [comment]
@mmacy https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1082 is tracking this activity.

**Comment by sameerag** [comment]
Samples update is expected to ship mid february from msal js which would be ported for the B2C use case around the same time.

**Comment by mmacy** [comment]
Thanks, @sameerag. Tagging in @msmimart for coordination of and update to the companion tutorials when the sample update is ready. We'll need to publish the updates simultaneously so the docs and the sample remain in sync.
