### ISSUE TITLE
Sample for v1.2.* ?

### ISSUE THREAD

**Issue by stephlocke** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#43]
Is it possible to for you to make a branch of this sample that corresponds to the next version of the msal.js lib? There's changes to the way redirects are handled and associated permissions that makes the latest version of this app on master not work 
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS:-1.2.0-beta.0#feature-iframes-support-and-performance-enhancements

**Comment by jennyf19** [comment]
@DarylThayil @sameerag Can you update this sample to the latest version of of msal. js? thanks.

**Comment by sameerag** [comment]
We fixed an issue with B2C that has issues with sandboxed iframes in `msal@1.2.0` and released `msal@1.2.1`. We will be updating all samples this week to reflect the same, this is currently not updated as the CDN release for `msal@1.2.1` is not yet made.

**Comment by sameerag** [comment]
CDN is now available and PR #47 is in progress to close this issue.

**Comment by stephlocke** [comment]
Thanks folks 👍

**Comment by jennyf19** [comment]
@sameerag this can be closed now right? i saw the PR was merged.

**Comment by sameerag** [comment]
Yes @jennyf19. Closing this as #47 is merged.
