### ISSUE TITLE
Does MSAL support device-specific authentication features (touchID, FaceID, etc...)?

### ISSUE THREAD

**Issue by mark-at-exelon** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#54]
Please provide any examples or information about MSAL's support for using device features like faceID, touchID, etc... (assuming B2C as IdP), and if that is not supported, please explain if that is planned. Thanks

**Comment by derisen** [comment]
msal.js is a token exchange library, meaning that it is concerned with acquisition of access tokens from identity providers and presentation of these tokens to protected resources. The authentication mechanism (user credentials, biometrics etc.) used by the IdP itself falls outside of the scope of the library. So this question falls more on the side of AAD B2C administration, in particular custom policies (@sameerag to confirm). In the meantime, I will pass a few resources that you can take a loot at:

[Authentication methods](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods)
[Passwordless authentication](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-passwordless)
[Custom policies samples](https://github.com/azure-ad-b2c/samples)
[Advanced policies samples](https://github.com/Azure-Samples/active-directory-b2c-advanced-policies)

**Comment by mark-at-exelon** [comment]
Will take a look at these, and already engaged with Microsoft on the policy question. Really appreciate the quick response. Thanks.

**Comment by mark-at-exelon** [comment]
Received update from Microsoft support: "there is not a solution for performing a biometric sign in into B2C and it is not planned in the near future, for this reason I would like to encourage you to leave us your feedback in order to improve azure Products in here https://feedback.azure.com/forums/169401-azure-active-directory"

**Comment by derisen** [comment]
sorry to hear that @mark-at-exelon -and thanks for informing us.
