### ISSUE TITLE
Missing how to handle 'Forgot your password' redirect

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#55]
Apparently when using a Sign Up/Sign In flow, clicking on the 'Forgot your Password' link will send an error back to the client. This tutorial is missing the handling of this error to show how we redirect the user to resetting their password.

Here is a stackoverflow link: https://stackoverflow.com/questions/41497158/azure-ad-b2c-self-service-password-reset-link-doesnt-work

And official docs: https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview#linking-user-flows

Appears there is an example in ASP .NET but not in JS 🙁

**Comment by derisen** [comment]
@Ethan-Arrowood good catch! I'll add this in the upcoming PR

**Comment by Ethan-Arrowood** [comment]
Thank you @derisen

**Comment by derisen** [comment]
Closing this as duplicate. For now, please checkout the `derisen-refactoring` branch for the interim solution.
