### ISSUE TITLE
SPA example code is invalid

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#57]
This part of authRedirect.js seems like a mistake:

https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/ef99a862a05445b55aaa76425a3cb6b4b01920b4/JavaScriptSPA/authRedirect.js#L22-L28

Maybe something was missed in the recent example rewrite?

**Comment by derisen** [comment]
Oh my.. Of course it should have been `if (accessToken !== null || accessToken !== undefined)` (or just `if (accessToken)`) instead! Thank you so much for this catch @Ethan-Arrowood -will fix that ASAP.
