### ISSUE TITLE
Sign In flow never appears

### ISSUE THREAD

**Issue by thomasando** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#59]
I'm attempting to get this working and am reasonably certain I've got it all configured correctly.

With authPopup.js being used for the Log In the popup window appears very briefly, loads no content and then disappears.

If I use authRedirect.js absolutely nothing happens - click the button and there's nothing. No change to page, no logs in node.js. I've tried heaps of browsers, multiple devices and always the same result.

Where am I going wrong?

**Comment by Uppanen** [comment]
I'm facing the same exact issue... I think it has something to do with the path that the login-dialog is trying to open. The url for the login adds "/v2.0/.well-known/openid-configuration" to the end of the login url and I can't get rid of it...

**Comment by Uppanen** [comment]
Got it fixed. My authority url was too specific. Got the answer from: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/259

**Comment by derisen** [comment]
@thomasando can you post your configuration? Is it possible that, like @theLadi , your authority string is too specific? It should just be just the domain and user flow part (the rest will be handled by msal.js), like:

`https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi`

**Comment by thomasando** [comment]
Thanks you!!! That's solved it.

For some reason I'd added some extra path into the URL - removed /oauth2/authresp and it's working. I have no idea why I did that but glad to say it's now fine!

`https://tenant.b2clogin.com/tenant.onmicrosoft.com/oauth2/authresp/B2C_1_testsusi`

**Comment by derisen** [comment]
Completely understandable, as that string appears at few places. We will try to make it more clear how the authority string should like like in configuration. 

Cheers.
