### ISSUE TITLE
Edit Profile policy?

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#6]
Great example! In the [documentation](https://azure.microsoft.com/en-gb/resources/samples/active-directory-b2c-javascript-msal-singlepageapp/) it's mentioned that edit profile policies are used, but I can't find them? That would be great to demo as well.

**Comment by blinkybill** [comment]
I still can't find them there either

**Comment by sameerag** [comment]
Tagging this with #48 and closing.
