### ISSUE TITLE
Web API & Scopes

### ISSUE THREAD

**Issue by marcosvidolin** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#64]
Hi guys,

Can you help me with the following questions?
I'm building a SPA to use B2C authentication, but I don't know why I have to create the "Web API".
Why do I need to create the "Web API" and what is and where I get the b2cScopes?

```javascript
const apiConfig = {
  b2cScopes: ["https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read"],
  webApi: "https://fabrikamb2chello.azurewebsites.net/hello"
};
```

Thank you

**Comment by derisen** [comment]
@marcosvidolin you don't really need to have a web api, it's just a common use case to couple a single-page application with a web api for data operations. 

If your aim is to just authenticate users to your b2c single-page app, simply remove the web api related code, or comment them out. (`apiConfig.js`, `api.js`, and anything else requests a token for the web api and calls it...)

The web api used in this sample is located [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi). Follow the instructions if you would like to use them together.

Hope this helps.

**Comment by marcosvidolin** [comment]
Thank you @derisen
