### ISSUE TITLE
How to use this with Authorization Code Flow?

### ISSUE THREAD

**Issue by kid101** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#68]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

How do I configure Authorization Code flow with this example?, Right now it doesn't seem to work, I referred [this sample](https://github.com/Azure-Samples/ms-identity-javascript-v2) to get the auth code flow working by added `knownAuthorities` in the auth configuration and enabling `publicClient Type` for the registered B2C application in the portal but not sure how to configure other policy like forgot password and profile edit in that. A better sample is needed. Any pinpoints or directions will also help thanks. 

PS: I'm aware of the existing [CROS issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1795) which would hopefully get resolved this month but looking better samples and docs. I thank you in advance,

**Comment by derisen** [comment]
@kid101 a new sample with a guide for auth code is on the line; we are coordinating the release with the resolution of CORS issue. There's also a [dev sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2148/files#diff-30b2efb6922bc3d82d780174c49623cc) and a [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1997/files) in the line on MSAL.js repo that you can take a peek.

**Comment by derisen** [comment]
Closing this as no further action to take at the moment.
