### ISSUE TITLE
Using state in msal

### ISSUE THREAD

**Issue by sarahshul** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#7]
How do I pass the state parameter in the example? I saw there was an issue about the state, so i guess it is possible to use state in the example. But, I can't figure out how to use it and how to retrieve it after token is returned.

**Comment by jmprieur** [comment]
Hi @sarahshul : The state (of the state machine) is purely internal to the library . you should not interact with it.

**Comment by sarahshul** [comment]
Hi, 
I am talking about the state like mentioned in the issue: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/1

this is the one you are talking about? 

I saw that Azure allows to send state with custom value: 

https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc

If it is not usable - can you recommend about a way to pass a value to the signup - that I can use later on the callback method?

**Comment by DadvDadv** [comment]
Please, Add a entry point to create a custom state parameter.

Look at [http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html](http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html)
and at [https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-07#page-7](https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-07#page-7)
for the reason

And in the official documentation from Microsoft : [https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit)

you can found that : 

**state** | recommended | A value included in the request that will also be returned in the token response. It can be a string of any content that you wish. A randomly generated unique value is typically used for preventing cross-site request forgery attacks. **The state is also used to encode information about the user's state in the app before the authentication request occurred, such as the page or view they were on**.

**Comment by paulpce** [comment]
If I'm reading this right, this is a fairly important issue.

Am I right in reading that there is _no way to modify the state parameter_, in the request to the Azure AD authorize endpoint, as @DadvDadv has already quoted, to "encode information about the user's state in the app before the authentication request occurred, such as the page or view they were on"?

If there is (and there definitely should be), can someone share some sample code please?

**Comment by sameerag** [comment]
Latest [msal js] (https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS-1.2.X) supports user passing a `state` variable in the request API (`acquireTokenSilent` or `acquireTokenPopup` etc). 

```  javascript
const tokenRequest = {
    scopes: ["Mail.Read"],
    state: "userState"
};

//acquire a token silently
function getToken(tokenRequest) {
    return myMSALObj.acquireTokenSilent(tokenRequest).catch(function(error) {
        console.log("aquire token popup");
        // fallback to interaction when silent call fails
        return myMSALObj.acquireTokenPopup(tokenRequest).then(function (tokenResponse) {
        }).catch(function(error){
            logMessage("Failed token acquisition", error);
        });
   });
}
```

Closing this issue.
