### ISSUE TITLE
Which of these auth config values are considered secrets?

### ISSUE THREAD

**Issue by sidm1983** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#74]
## Description

I would like to know if any of the authConfig.js or apiConfig.js values should be considered secrets? I am currently building a web app that has a web API back-end and a React SPA front-end with Azure AD B2C authentication being done in the React SPA. Just like the sample in this repo, I have auth config hard-coded in my React/JS code. Please let me know if any of the following values should be considered secrets and if they should not be committed to my git repository:
- instance: 'https://\<b2cName\>.b2clogin.com/tfp/'
- tenant: '\<b2cName\>.onmicrosoft.com'
- signInPolicy: '\<signInPolicyName\>'
- clientId: '\<client-guid\>'
- scopes: ['https://\<b2cName\>.onmicrosoft.com/\<b2cAppName\>/\<scopeName\>']

In my web API's `appsettings.json`, I have all of the above settings as well as the following additional settings:
- tenantId: '\<tenant-guid\>'
- authority: 'https://\<b2cName\>.b2clogin.com/tfp/\<b2cName\>.onmicrosoft.com/\<signInPolicyName\>/v2.0'
- audience: 'https://\<b2cName\>.onmicrosoft.com/\<b2cAppName\>'

Please let me know if any of the above values are considered secrets so I can make sure I don't commit secret values into my git repo.

Any help is appreciated. Thank you! 🙏🏽

**Comment by jasonnutter** [comment]
None of these are considered secrets. MSAL.js implements public client applications because web browsers are not capable of securely storing secrets.

**Comment by sidm1983** [comment]
@jasonnutter I figured as much, but just wanted to be sure. Thanks for confirming. ☺️🙌🏽
