### ISSUE TITLE
What Is The Recommended Way To Test This?

### ISSUE THREAD

**Issue by opticyclic** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#75]
## Library

 - "msal": "^1.4.0",
 - "react-aad-msal": "^2.3.5",

## Description

After successfully following this guide and having an email signup/login process integrated with my application I would like to do an end to end test.

However, this seems to cause problems with Cypress

https://stackoverflow.com/questions/57476816/handling-cypress-url-redirect

https://github.com/cypress-io/cypress/issues/1342

What is the recommended way to test this?

**Comment by derisen** [comment]
@opticyclic we do not have an official guideline for testing with cypress. However the samples in the main MSAL.js repository has e2e tests (mainly using Pupeeter). See [this for msal.js 1.x](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/VanillaJSTestApp) and [this for msal.js 2.x](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app)

**Comment by Wenish** [comment]
@derisen would it be possible to update it with an example which uses cypress?

**Comment by derisen** [comment]
@Wenish we can certainly put this in the backlog, but I'm not able to give an ETA for the moment. If your testing need is urgent I'm afraid the links I gave above are the only alternative.

**Comment by derisen** [comment]
@Wenish we discussed providing guidance for automated testing for MSAL.js, however this is planned for after new year. Closing this as no further action to take at the moment.
