### ISSUE TITLE
Redirect callback needs to updateUI()

### ISSUE THREAD

**Issue by Nathan-Devery** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#79]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
On line 67 (after 'console.log("Token type is: " + response.tokenType);'), updateUI() needs to be added so the UI updates - showing the buttons for the subsequent calls.

## Security

- [ ] Is this issue security related?

## Regression

- [ ] Did this behavior work before?

Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by derisen** [comment]
@Nathan-Devery thanks a lot catching this! If you like, feel free to make a PR for it and add me as a reviewer.

**Comment by derisen** [comment]
On second thought, this seems intentional as if the token type cannot be determined, the ui shouldn't be updated. Closing.
