### ISSUE TITLE
Open register window

### ISSUE THREAD

**Issue by sarahshul** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#8]
Hi,

Is there a way to open directly the Create New Account window?

I have a case where I know it is a new account, and I dont want to allow user to do login, I also dont want to show him the login window and force him to press the create new account link.

Thank you.

**Comment by parakhj** [comment]
You could set up and call a sign up policy for that particular case

**Comment by sameerag** [comment]
Closing as addressed by @parakhj
